from snakemake.utils import min_version

min_version("6.4.1")

configfile: "config/config.yaml"

include: "rules/data.smk"
include: "rules/orthologues.smk"

rule all:
    input:
        expand("resources/sequences/{species}.pep.fasta", species=targets.index),
        get_orthofinder_outdir(),
        expand("results/emapper/{species}/{species}.pep.emapper.annotations", species=targets.index),
        "results/annotations/resolved_gene_trees.master.annotated.txt"
